# {{title}} — Pi Entrypoint

This Pi workspace is a deterministic projection of the `.claude/` SSOT,
generated by `papersmith` {{version}}.

Read `papersmith.yaml`, `guidance/paper-guide/`, and the applicable
`skills/*/SKILL.md` before working on the paper.

## Agents

{{agents}}
