"""From-scratch command series: every ``papersmith`` command over a CLI-made workspace.

Layer purpose. The paper journey (``test_cli_paper_e2e.py``) walks the research
flow once; this module proves the other half of the product claim: that a
workspace generated by ``papersmith init`` is a working instrument for *every*
command the CLI advertises, including the ones the journey never touches
(``upgrade``, ``target``). Deep engine legs stay in their own suites; every
test here starts from ``init`` and drives the CLI as a user would.

Boundaries stay hermetic: stubbed ingest, symlinked ``node_modules``, dry-run
dispatch, no network, no model calls, no live Kaggle.
"""

from __future__ import annotations

import ast
import contextlib
import io
import json
import os
import subprocess
import unittest
from pathlib import Path
from unittest import mock

from papersmith.cli import main
from papersmith.core import ledger as run_ledger
from papersmith.core.exit_codes import DRIFT_ERROR, SUCCESS, USER_ERROR

from workspace_series import (
    FIXTURE_PDF,
    REPO_ROOT,
    capture,
    link_node_modules,
    make_demo_target,
    make_workspace,
    new_tmp,
    stub_extract,
)

COMMANDS = (
    "init",
    "upgrade",
    "status",
    "ingest",
    "deliberate",
    "implement",
    "run",
    "remote",
    "target",
    "audit",
)


def _help_door(command: str):
    """Run ``<command> --help`` and return ``(exit code, printed help)``."""
    buffer = io.StringIO()
    try:
        with contextlib.redirect_stdout(buffer):
            main([command, "--help"])
    except SystemExit as exc:
        return exc.code, buffer.getvalue()
    raise AssertionError(f"{command} --help did not exit through SystemExit")


class CommandRosterTests(unittest.TestCase):
    """Every advertised command answers its own front door."""

    def test_every_command_has_a_working_help_door(self) -> None:
        for command in COMMANDS:
            with self.subTest(command=command):
                code, text = _help_door(command)
                self.assertEqual(code, 0, f"{command} --help must exit 0")
                self.assertIn("usage:", text, f"{command} printed no usage")

    def test_version_is_a_top_level_flag(self) -> None:
        buffer = io.StringIO()
        with contextlib.redirect_stdout(buffer):
            with self.assertRaises(SystemExit) as caught:
                main(["--version"])
        self.assertEqual(caught.exception.code, 0)
        self.assertIn("papersmith", buffer.getvalue())


class GeneratedWorkspaceTests(unittest.TestCase):
    """``init`` from the CLI is the only generator used by this series."""

    def test_init_creates_a_ready_workspace(self) -> None:
        workspace = make_workspace(new_tmp(self))
        for relpath in (
            ".papersmith/manifest.json",
            ".papersmith/config.json",
            ".papersmith/version",
            "papersmith.yaml",
            "CLAUDE.md",
            "OPENCODE.md",
            "PI.md",
            ".pi/gentle-ai/persona.json",
            ".antigravity/rules.md",
            "README.md",
            "DECISIONS.md",
            "journal/README.md",
            "skills/paper-writing/SKILL.md",
            "skills/proposal-deliberation/cli.mjs",
            "scripts/setup_env.py",
            "scripts/setup-harnesses.sh",
        ):
            self.assertTrue((workspace / relpath).exists(), relpath)
        rc, out, _ = capture(["status", str(workspace), "--json"])
        self.assertEqual(rc, SUCCESS)
        payload = json.loads(out)
        self.assertEqual(payload["project_name"], "series-ws")
        self.assertEqual(payload["framework"]["drifted_files"], [])
        self.assertTrue(payload["framework"]["version_match"])

    def test_status_names_drift_without_failing(self) -> None:
        # Documented known gap: status reports drift by name and still exits 0.
        workspace = make_workspace(new_tmp(self))
        claude = workspace / "CLAUDE.md"
        claude.write_text(claude.read_text(encoding="utf-8") + "\n<!-- probe -->\n",
                          encoding="utf-8")
        rc, out, _ = capture(["status", str(workspace)])
        self.assertEqual(rc, SUCCESS)
        self.assertIn("CLAUDE.md", out)


class UpgradeCommandTests(unittest.TestCase):

    def test_upgrade_restores_framework_files_and_preserves_research(self) -> None:
        workspace = make_workspace(new_tmp(self))
        skill = workspace / "skills/paper-ingestion/SKILL.md"
        original = skill.read_bytes()
        skill.write_bytes(b"tampered by the test\n")
        research = workspace / "journal/notes.md"
        research.write_text("research stays\n", encoding="utf-8")
        rc, out, _ = capture(["upgrade", str(workspace)])
        self.assertEqual(rc, SUCCESS)
        self.assertIn("Upgraded papersmith workspace", out)
        self.assertEqual(skill.read_bytes(), original, "upgrade must restore framework bytes")
        self.assertEqual(research.read_text(encoding="utf-8"), "research stays\n")
        rc, out, _ = capture(["audit", str(workspace), "--check-drift"])
        self.assertEqual(rc, SUCCESS)
        self.assertIn("drift: clean", out)


class HarnessProjectionTests(unittest.TestCase):
    """The workspace ships the script its package.json advertises for harness wiring."""

    HARNESS_LINKS = (".claude/skills", ".pi/skills", ".opencode/skills", ".antigravity/skills")

    def test_projection_script_wires_every_harness(self) -> None:
        workspace = make_workspace(new_tmp(self))
        package = (workspace / "package.json").read_text(encoding="utf-8")
        self.assertIn("bash scripts/setup-harnesses.sh", package)
        script = workspace / "scripts" / "setup-harnesses.sh"
        self.assertTrue(script.is_file(), "the workspace must ship the script it advertises")

        first = subprocess.run(
            ["bash", str(script)], cwd=workspace, capture_output=True, text=True, timeout=60,
        )
        self.assertEqual(first.returncode, 0, first.stderr)
        for relpath in self.HARNESS_LINKS:
            link = workspace / relpath
            self.assertTrue(link.is_symlink(), f"{relpath} must be a symlink")
            self.assertEqual(os.readlink(link), os.path.relpath(workspace / "skills", link.parent))
            self.assertTrue((link / "paper-ingestion" / "SKILL.md").is_file(), relpath)

        second = subprocess.run(
            ["bash", str(script)], cwd=workspace, capture_output=True, text=True, timeout=60,
        )
        self.assertEqual(second.returncode, 0, second.stderr)
        for relpath in self.HARNESS_LINKS:
            self.assertTrue((workspace / relpath).is_symlink(), f"{relpath} must survive a re-run")


class HarnessCommandProjectionTests(unittest.TestCase):
    """The nine skills arrive as slash commands, plus the OpenCode safety plugin."""

    COMMAND_NAMES = (
        "experimental-deliberation",
        "experimental-implementation",
        "kaggle-accounts",
        "paper-ingestion",
        "paper-writing",
        "proposal-deliberation",
        "proposal-implementation",
        "remote-execution",
        "skill-audit",
    )

    def test_init_projects_nine_commands_per_command_harness(self) -> None:
        workspace = make_workspace(new_tmp(self))
        for harness in (".opencode/commands", ".claude/commands"):
            with self.subTest(harness=harness):
                names = sorted(path.stem for path in (workspace / harness).glob("*.md"))
                self.assertEqual(names, sorted(self.COMMAND_NAMES))
                body = (workspace / harness / "paper-ingestion.md").read_text(encoding="utf-8")
                self.assertIn("$ARGUMENTS", body)
                self.assertIn("skills/paper-ingestion/SKILL.md", body)

    def test_non_command_harnesses_receive_no_command_directory(self) -> None:
        workspace = make_workspace(new_tmp(self))
        self.assertFalse((workspace / ".pi/commands").exists())
        self.assertFalse((workspace / ".antigravity/commands").exists())

    def test_opencode_json_is_valid_and_declares_no_plugin_key(self) -> None:
        workspace = make_workspace(new_tmp(self))
        payload = json.loads((workspace / "opencode.json").read_text(encoding="utf-8"))
        self.assertEqual(payload["$schema"], "https://opencode.ai/config.json")
        self.assertIn("permission", payload)
        self.assertNotIn("plugin", payload,
                         "plugins are auto-discovered; a plugin key would duplicate that")

    def test_opencode_plugin_is_the_generated_relay(self) -> None:
        workspace = make_workspace(new_tmp(self))
        text = (workspace / ".opencode/plugins/refuse-offpath-push.js").read_text(encoding="utf-8")
        self.assertIn("export const server", text)
        self.assertIn("tool.execute.before", text)
        self.assertIn("_load_push_surfaces", text)

    def test_audit_is_clean_and_upgrade_restores_a_tampered_command(self) -> None:
        workspace = make_workspace(new_tmp(self))
        rc, out, _ = capture(["audit", str(workspace), "--check-drift"])
        self.assertEqual(rc, SUCCESS)
        self.assertIn("drift: clean", out)

        command = workspace / ".opencode/commands/paper-writing.md"
        original = command.read_bytes()
        command.write_bytes(b"tampered\n")
        rc, out, _ = capture(["audit", str(workspace), "--check-drift"])
        self.assertEqual(rc, DRIFT_ERROR)
        self.assertIn(".opencode/commands/paper-writing.md", out)
        self.assertEqual(command.read_bytes(), b"tampered\n", "audit must never repair")

        rc, _, _ = capture(["upgrade", str(workspace)])
        self.assertEqual(rc, SUCCESS)
        self.assertEqual(command.read_bytes(), original)


class TargetCommandTests(unittest.TestCase):

    def test_target_list_set_and_check_round_trip(self) -> None:
        workspace = make_workspace(new_tmp(self))
        rc, out, _ = capture(["target", "list", str(workspace)])
        self.assertEqual(rc, SUCCESS)
        self.assertIn("local-workstation: local *", out)
        self.assertIn("kaggle-gpu-pool: kaggle", out)
        self.assertIn("slurm-cluster: remote-ssh", out)

        rc, out, _ = capture(["target", "set", "local-workstation", str(workspace)])
        self.assertEqual(rc, SUCCESS)
        self.assertIn("Active target: local-workstation (local)", out)

        rc, out, _ = capture(["target", "check", "local-workstation", str(workspace)])
        self.assertEqual(rc, SUCCESS)
        result = ast.literal_eval(out.strip())
        self.assertEqual(result["provider"], "local")
        self.assertTrue(result["reachable"])

    def test_target_set_refuses_an_unknown_name(self) -> None:
        workspace = make_workspace(new_tmp(self))
        rc, _, err = capture(["target", "set", "gpu-cloud", str(workspace)])
        self.assertEqual(rc, USER_ERROR)
        self.assertIn("unknown compute target", err)


class RunCommandTests(unittest.TestCase):

    def test_run_dry_run_records_a_row_without_dispatching(self) -> None:
        workspace = make_workspace(new_tmp(self))
        dispatched = False

        def _fail_if_dispatched(*args, **kwargs):
            nonlocal dispatched
            dispatched = True
            raise AssertionError("dry-run dispatched a subprocess")

        with mock.patch("papersmith.core.executor.subprocess.run",
                        side_effect=_fail_if_dispatched):
            rc, out, err = capture(["run", "smoke_and_invariants", "--dry-run", str(workspace)])
        self.assertEqual(rc, SUCCESS)
        self.assertFalse(dispatched)
        self.assertIn("dry-run: no job was dispatched", err)
        payload = json.loads(out)
        self.assertTrue(payload["jobs"][0]["dry_run"])
        self.assertTrue(run_ledger.read(workspace)[0]["dry_run"])


class AuditCommandTests(unittest.TestCase):

    def test_audit_detects_drift_and_never_repairs_it(self) -> None:
        workspace = make_workspace(new_tmp(self))
        rc, out, _ = capture(["audit", str(workspace), "--check-drift"])
        self.assertEqual(rc, SUCCESS)
        self.assertIn("drift: clean", out)

        claude = workspace / "CLAUDE.md"
        claude.write_text(claude.read_text(encoding="utf-8") + "\n<!-- audit probe -->\n",
                          encoding="utf-8")
        rc, out, _ = capture(["audit", str(workspace), "--check-drift"])
        self.assertEqual(rc, DRIFT_ERROR)
        self.assertIn("CLAUDE.md", out)
        self.assertIn("<!-- audit probe -->", claude.read_text(encoding="utf-8"))


class RemoteCommandTests(unittest.TestCase):

    def test_remote_push_refuses_before_its_required_flags_are_named(self) -> None:
        workspace = make_workspace(new_tmp(self))
        rc, _, err = capture(["remote", "push", str(workspace)])
        self.assertEqual(rc, USER_ERROR)
        self.assertIn("remote push requires", err)

    def test_remote_status_refuses_an_unresolvable_job_target(self) -> None:
        workspace = make_workspace(new_tmp(self))
        missing = workspace / "implementations" / "missing"
        rc, _, err = capture(
            ["remote", "status", "--target", str(missing),
             "--entrypoint", "Notebooks/a.ipynb", str(workspace)]
        )
        self.assertNotEqual(rc, SUCCESS)
        self.assertIn("does not resolve to an existing directory", err)
        self.assertFalse(missing.exists(), "a refused status must touch nothing")


class DeliberateImplementCommandTests(unittest.TestCase):

    def test_deliberate_engine_runs_and_implement_probes_in_one_workspace(self) -> None:
        workspace = make_workspace(new_tmp(self))
        link_node_modules(workspace)
        token = f"series-{os.getpid()}"

        rc, out, _ = capture([
            "deliberate", str(workspace), "--action", "init",
            "--instruction", f"{token}. The series walks the workspace engine.",
        ])
        self.assertEqual(rc, SUCCESS)
        created = json.loads(out)
        target = created["targetFilename"]
        self.assertTrue(target.endswith("-r01.md"))
        self.assertTrue((workspace / "proposals" / target).is_file())

        rc, out, _ = capture(["deliberate", str(workspace), "--action", "status"])
        self.assertEqual(rc, SUCCESS)
        self.assertEqual(json.loads(out)["latest"], target)

        make_demo_target(workspace)
        rc, out, _ = capture([
            "implement", str(workspace), "--action", "probe",
            "--target", "implementations/demo", "--name", "Demo",
        ])
        self.assertEqual(rc, SUCCESS)
        payload = json.loads(out)
        self.assertEqual(payload["status"], "ok")
        self.assertTrue(payload["nextStep"])
        self.assertEqual(list((workspace / "implementations" / "demo").rglob("*.ipynb")), [])


class IngestCommandTests(unittest.TestCase):

    def test_ingest_stubbed_lands_markdown_figure_and_index(self) -> None:
        workspace = make_workspace(new_tmp(self))
        with stub_extract():
            rc, out, _ = capture(["ingest", str(FIXTURE_PDF), str(workspace)])
        self.assertEqual(rc, SUCCESS)
        self.assertIn("Ingested:", out)
        paper_dir = workspace / "guidance" / "reference-papers" / "paper"
        markdown = (paper_dir / "paper.md").read_text(encoding="utf-8")
        self.assertIn(r"\tag", markdown)
        self.assertTrue((paper_dir / "_page_1_Figure_1.png").is_file())
        index = json.loads(
            (workspace / "guidance" / "reference-papers" / "index.json").read_text(encoding="utf-8")
        )
        self.assertTrue(any(entry["id"] == "paper" for entry in index["entries"]))


class LiveSmokeScriptTests(unittest.TestCase):
    """The opt-in live smoke is a contract of this series, not a suggestion."""

    SCRIPT = REPO_ROOT / "scripts" / "cli-paper-live-smoke.sh"

    def test_script_exists_executable_and_covers_every_command(self) -> None:
        self.assertTrue(self.SCRIPT.is_file(), "missing scripts/cli-paper-live-smoke.sh")
        self.assertTrue(os.access(self.SCRIPT, os.X_OK), "live smoke must be executable")
        text = self.SCRIPT.read_text(encoding="utf-8")
        for command in COMMANDS:
            self.assertIn(command, text, f"live smoke must cover {command}")
        self.assertIn("PAPERSMITH_LIVE", text, "live smoke must be explicitly opt-in")

    def test_script_refuses_to_run_without_opt_in(self) -> None:
        env = {key: value for key, value in os.environ.items() if key != "PAPERSMITH_LIVE"}
        completed = subprocess.run(
            ["bash", str(self.SCRIPT), str(new_tmp(self))],
            capture_output=True, text=True, timeout=60, env=env,
        )
        self.assertNotEqual(completed.returncode, 0, "live smoke ran without PAPERSMITH_LIVE")
        self.assertIn("PAPERSMITH_LIVE", completed.stderr + completed.stdout)

    def test_hermetic_smoke_wrapper_still_exists(self) -> None:
        hermetic = REPO_ROOT / "scripts" / "cli-paper-smoke.sh"
        self.assertTrue(hermetic.is_file())
        self.assertTrue(os.access(hermetic, os.X_OK))


class SeriesRegistrationTests(unittest.TestCase):
    """The series registers itself in the SDD testing layers it belongs to."""

    def test_series_files_are_registered_in_config(self) -> None:
        text = (REPO_ROOT / "openspec" / "config.yaml").read_text(encoding="utf-8")
        for name in (
            "test_workspace_commands_e2e",
            "test_workspace_skills_e2e",
            "test_workspace_agents_e2e",
        ):
            self.assertIn(name, text, f"{name} must appear in openspec/config.yaml")
